<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpeg_peraturan extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Peraturan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $simpeg_peraturan = $this->Peraturan_model->get_all();

        $data = array(
            'simpeg_peraturan_data' => $simpeg_peraturan
        );

        $this->template->display('simpeg_master_peraturan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Peraturan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_peraturan' => $row->id_peraturan,
		'nama_peraturan' => $row->nama_peraturan,
	    );
            $this->template->display('simpeg_master_peraturan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_peraturan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('simpeg_peraturan/create_action'),
	    'id_peraturan' => set_value('id_peraturan'),
	    'nama_peraturan' => set_value('nama_peraturan'),
	);
        $this->template->display('simpeg_master_peraturan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_peraturan' => $this->input->post('nama_peraturan',TRUE),
	    );

            $this->Peraturan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('simpeg_peraturan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Peraturan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('simpeg_peraturan/update_action'),
		'id_peraturan' => set_value('id_peraturan', $row->id_peraturan),
		'nama_peraturan' => set_value('nama_peraturan', $row->nama_peraturan),
	    );
            $this->template->display('simpeg_master_peraturan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_peraturan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_peraturan', TRUE));
        } else {
            $data = array(
		'nama_peraturan' => $this->input->post('nama_peraturan',TRUE),
	    );

            $this->Peraturan_model->update($this->input->post('id_peraturan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('simpeg_peraturan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Peraturan_model->get_by_id($id);

        if ($row) {
            $this->Peraturan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('simpeg_peraturan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_peraturan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_peraturan', 'nama peraturan', 'trim|required');

	$this->form_validation->set_rules('id_peraturan', 'id_peraturan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Simpeg_peraturan.php */
/* Location: ./application/controllers/Simpeg_peraturan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-27 20:59:05 */
/* http://harviacode.com */