<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sima_master_lokasi extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Model_sima_lokasi');
        chek_session();
        cek_menu();
    }

    public function index() {
        $sima_master_lokasi = $this->Model_sima_lokasi->get_all();

        $data = array(
            'sima_master_lokasi_data' => $sima_master_lokasi
        );

        $this->template->display('sima_master_lokasi_list', $data);
    }

    public function read($id) {
        $row = $this->Model_sima_lokasi->get_by_id($id);
        if ($row) {
            $data = array(
                'id_lokasi' => $row->id_lokasi,
                'lokasi' => $row->lokasi,
                'keterangan_lokasi' => $row->keterangan_lokasi,
            );
            $this->template->display('sima_master_lokasi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_lokasi'));
        }
    }

    public function create() {
        $data = array(
            'button' => 'Create',
            'action' => site_url('sima_master_lokasi/create_action'),
            'id_lokasi' => set_value('id_lokasi'),
            'lokasi' => set_value('lokasi'),
            'keterangan_lokasi' => set_value('keterangan_lokasi'),
        );
        $this->template->display('sima_master_lokasi_form', $data);
    }

    public function create_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'lokasi' => $this->input->post('lokasi', TRUE),
                'keterangan_lokasi' => $this->input->post('keterangan_lokasi', TRUE),
            );

            $this->Model_sima_lokasi->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sima_master_lokasi'));
        }
    }

    public function update($id) {
        $row = $this->Model_sima_lokasi->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('sima_master_lokasi/update_action'),
                'id_lokasi' => set_value('id_lokasi', $row->id_lokasi),
                'lokasi' => set_value('lokasi', $row->lokasi),
                'keterangan_lokasi' => set_value('keterangan_lokasi', $row->keterangan_lokasi),
            );
            $this->template->display('sima_master_lokasi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_lokasi'));
        }
    }

    public function update_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_lokasi', TRUE));
        } else {
            $data = array(
                'lokasi' => $this->input->post('lokasi', TRUE),
                'keterangan_lokasi' => $this->input->post('keterangan_lokasi', TRUE),
            );

            $this->Model_sima_lokasi->update($this->input->post('id_lokasi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sima_master_lokasi'));
        }
    }

    public function delete($id) {
        $row = $this->Model_sima_lokasi->get_by_id($id);

        if ($row) {
            $this->Model_sima_lokasi->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sima_master_lokasi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_lokasi'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('lokasi', 'lokasi', 'trim|required');
        $this->form_validation->set_rules('keterangan_lokasi', 'keterangan lokasi', 'trim|required');

        $this->form_validation->set_rules('id_lokasi', 'id_lokasi', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Sima_master_lokasi.php */
/* Location: ./application/controllers/Sima_master_lokasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-31 06:14:24 */
/* http://harviacode.com */