<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpeg_status_pegawai extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_pegawai_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $simpeg_status_pegawai = $this->Status_pegawai_model->get_all();

        $data = array(
            'simpeg_status_pegawai_data' => $simpeg_status_pegawai
        );

        $this->template->display('simpeg_master_status_pegawai_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Status_pegawai_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_status' => $row->id_status,
		'nama_status' => $row->nama_status,
	    );
            $this->template->display('simpeg_master_status_pegawai_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_status_pegawai'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('simpeg_status_pegawai/create_action'),
	    'id_status' => set_value('id_status'),
	    'nama_status' => set_value('nama_status'),
	);
        $this->template->display('simpeg_master_status_pegawai_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_status' => $this->input->post('nama_status',TRUE),
	    );

            $this->Status_pegawai_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('simpeg_status_pegawai'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Status_pegawai_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('simpeg_status_pegawai/update_action'),
		'id_status' => set_value('id_status', $row->id_status),
		'nama_status' => set_value('nama_status', $row->nama_status),
	    );
            $this->template->display('simpeg_master_status_pegawai_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_status_pegawai'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_status', TRUE));
        } else {
            $data = array(
		'nama_status' => $this->input->post('nama_status',TRUE),
	    );

            $this->Status_pegawai_model->update($this->input->post('id_status', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('simpeg_status_pegawai'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Status_pegawai_model->get_by_id($id);

        if ($row) {
            $this->Status_pegawai_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('simpeg_status_pegawai'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_status_pegawai'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_status', 'nama status', 'trim|required');

	$this->form_validation->set_rules('id_status', 'id_status', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Simpeg_status_pegawai.php */
/* Location: ./application/controllers/Simpeg_status_pegawai.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-27 20:35:28 */
/* http://harviacode.com */