<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sima_master_status extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Model_sima_status');
        chek_session();
        cek_menu();
    }

    public function index() {
        $sima_master_status = $this->Model_sima_status->get_all();

        $data = array(
            'sima_master_status_data' => $sima_master_status
        );

        $this->template->display('sima_master_status_list', $data);
    }

    public function read($id) {
        $row = $this->Model_sima_status->get_by_id($id);
        if ($row) {
            $data = array(
                'id_status' => $row->id_status,
                'status' => $row->status,
                'keterangan_status' => $row->keterangan_status,
            );
            $this->template->display('sima_master_status_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_status'));
        }
    }

    public function create() {
        $data = array(
            'button' => 'Create',
            'action' => site_url('sima_master_status/create_action'),
            'id_status' => set_value('id_status'),
            'status' => set_value('status'),
            'keterangan_status' => set_value('keterangan_status'),
        );
        $this->template->display('sima_master_status_form', $data);
    }

    public function create_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'status' => $this->input->post('status', TRUE),
                'keterangan_status' => $this->input->post('keterangan_status', TRUE),
            );

            $this->Model_sima_status->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sima_master_status'));
        }
    }

    public function update($id) {
        $row = $this->Model_sima_status->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('sima_master_status/update_action'),
                'id_status' => set_value('id_status', $row->id_status),
                'status' => set_value('status', $row->status),
                'keterangan_status' => set_value('keterangan_status', $row->keterangan_status),
            );
            $this->template->display('sima_master_status_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_status'));
        }
    }

    public function update_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_status', TRUE));
        } else {
            $data = array(
                'status' => $this->input->post('status', TRUE),
                'keterangan_status' => $this->input->post('keterangan_status', TRUE),
            );

            $this->Model_sima_status->update($this->input->post('id_status', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sima_master_status'));
        }
    }

    public function delete2($id) {
        $row = $this->Model_sima_status->get_by_id($id);

        if ($row) {
            $this->Model_sima_status->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sima_master_status'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_status'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('status', 'status', 'trim|required');
        $this->form_validation->set_rules('keterangan_status', 'keterangan status', 'trim|required');

        $this->form_validation->set_rules('id_status', 'id_status', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Sima_master_status.php */
/* Location: ./application/controllers/Sima_master_status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-31 07:37:43 */
/* http://harviacode.com */