<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpeg_visi_misi extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Visi_misi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $simpeg_visi_misi = $this->Visi_misi_model->get_all();

        $data = array(
            'simpeg_visi_misi_data' => $simpeg_visi_misi
        );

        $this->template->display('simpeg_master_visimisi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Visi_misi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_visimisi' => $row->id_visimisi,
		'visimisi' => $row->visimisi,
	    );
            $this->template->display('simpeg_master_visimisi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_visi_misi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('simpeg_visi_misi/create_action'),
	    'id_visimisi' => set_value('id_visimisi'),
	    'visimisi' => set_value('visimisi'),
	);
        $this->template->display('simpeg_master_visimisi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'visimisi' => $this->input->post('visimisi',TRUE),
	    );

            $this->Visi_misi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('simpeg_visi_misi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Visi_misi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('simpeg_visi_misi/update_action'),
		'id_visimisi' => set_value('id_visimisi', $row->id_visimisi),
		'visimisi' => set_value('visimisi', $row->visimisi),
	    );
            $this->template->display('simpeg_master_visimisi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_visi_misi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_visimisi', TRUE));
        } else {
            $data = array(
		'visimisi' => $this->input->post('visimisi',TRUE),
	    );

            $this->Visi_misi_model->update($this->input->post('id_visimisi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('simpeg_visi_misi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Visi_misi_model->get_by_id($id);

        if ($row) {
            $this->Visi_misi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('simpeg_visi_misi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_visi_misi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('visimisi', 'visimisi', 'trim|required');

	$this->form_validation->set_rules('id_visimisi', 'id_visimisi', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Simpeg_visi_misi.php */
/* Location: ./application/controllers/Simpeg_visi_misi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-27 21:40:06 */
/* http://harviacode.com */