<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sima_master_kategori extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Model_sima_kategori');
        chek_session();
        cek_menu();
    }

    public function index() {
        $sima_master_kategori = $this->Model_sima_kategori->get_all();

        $data = array(
            'sima_master_kategori_data' => $sima_master_kategori
        );

        $this->template->display('sima_master_kategori_list', $data);
    }

    public function read($id) {
        $row = $this->Model_sima_kategori->get_by_id($id);
        if ($row) {
            $data = array(
                'id_kategori' => $row->id_kategori,
                'kategori' => $row->kategori,
                'keterangan_kategori' => $row->keterangan_kategori,
            );
            $this->template->display('sima_master_kategori_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_kategori'));
        }
    }

    public function create() {
        $data = array(
            'button' => 'Create',
            'action' => site_url('sima_master_kategori/create_action'),
            'id_kategori' => set_value('id_kategori'),
            'kategori' => set_value('kategori'),
            'keterangan_kategori' => set_value('keterangan_kategori'),
        );
        $this->template->display('sima_master_kategori_form', $data);
    }

    public function create_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'kategori' => $this->input->post('kategori', TRUE),
                'keterangan_kategori' => $this->input->post('keterangan_kategori', TRUE),
            );

            $this->Model_sima_kategori->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sima_master_kategori'));
        }
    }

    public function update($id) {
        $row = $this->Model_sima_kategori->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('sima_master_kategori/update_action'),
                'id_kategori' => set_value('id_kategori', $row->id_kategori),
                'kategori' => set_value('kategori', $row->kategori),
                'keterangan_kategori' => set_value('keterangan_kategori', $row->keterangan_kategori),
            );
            $this->template->display('sima_master_kategori_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_kategori'));
        }
    }

    public function update_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kategori', TRUE));
        } else {
            $data = array(
                'kategori' => $this->input->post('kategori', TRUE),
                'keterangan_kategori' => $this->input->post('keterangan_kategori', TRUE),
            );

            $this->Model_sima_kategori->update($this->input->post('id_kategori', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sima_master_kategori'));
        }
    }

    public function delete($id) {
        $row = $this->Model_sima_kategori->get_by_id($id);

        if ($row) {
            $this->Model_sima_kategori->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sima_master_kategori'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sima_master_kategori'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('kategori', 'kategori', 'trim|required');
        $this->form_validation->set_rules('keterangan_kategori', 'keterangan kategori', 'trim|required');

        $this->form_validation->set_rules('id_kategori', 'id_kategori', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Sima_master_kategori.php */
/* Location: ./application/controllers/Sima_master_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-31 05:00:46 */
/* http://harviacode.com */