<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpeg_lokasi_pelatihan extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lokasi_pelatihan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $simpeg_lokasi_pelatihan = $this->Lokasi_pelatihan_model->get_all();

        $data = array(
            'simpeg_lokasi_pelatihan_data' => $simpeg_lokasi_pelatihan
        );

        $this->template->display('simpeg_master_lokasi_pelatihan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Lokasi_pelatihan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_lokasi' => $row->id_lokasi,
		'nama_lokasi' => $row->nama_lokasi,
	    );
            $this->template->display('simpeg_master_lokasi_pelatihan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_lokasi_pelatihan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('simpeg_lokasi_pelatihan/create_action'),
	    'id_lokasi' => set_value('id_lokasi'),
	    'nama_lokasi' => set_value('nama_lokasi'),
	);
        $this->template->display('simpeg_master_lokasi_pelatihan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_lokasi' => $this->input->post('nama_lokasi',TRUE),
	    );

            $this->Lokasi_pelatihan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('simpeg_lokasi_pelatihan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Lokasi_pelatihan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('simpeg_lokasi_pelatihan/update_action'),
		'id_lokasi' => set_value('id_lokasi', $row->id_lokasi),
		'nama_lokasi' => set_value('nama_lokasi', $row->nama_lokasi),
	    );
            $this->template->display('simpeg_master_lokasi_pelatihan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_lokasi_pelatihan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_lokasi', TRUE));
        } else {
            $data = array(
		'nama_lokasi' => $this->input->post('nama_lokasi',TRUE),
	    );

            $this->Lokasi_pelatihan_model->update($this->input->post('id_lokasi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('simpeg_lokasi_pelatihan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Lokasi_pelatihan_model->get_by_id($id);

        if ($row) {
            $this->Lokasi_pelatihan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('simpeg_lokasi_pelatihan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('simpeg_lokasi_pelatihan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_lokasi', 'nama lokasi', 'trim|required');

	$this->form_validation->set_rules('id_lokasi', 'id_lokasi', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Simpeg_lokasi_pelatihan.php */
/* Location: ./application/controllers/Simpeg_lokasi_pelatihan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-27 20:10:44 */
/* http://harviacode.com */