<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pelatihan_model extends CI_Model
{

    public $table = 'simpeg_data_pelatihan';
    public $id = 'id_data_pelatihan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    
    function get_data(){
        $getdata = $this->db->query("SELECT simpeg_data_pelatihan.id_data_pelatihan,simpeg_data_pegawai.nip,simpeg_data_pegawai.nama_pegawai,simpeg_master_pelatihan.nama_pelatihan,
            simpeg_master_pelatihan.jenis_pelatihan,simpeg_master_lokasi_pelatihan.nama_lokasi,simpeg_data_pelatihan.tanggal,simpeg_data_pelatihan.penyelenggara,simpeg_data_pelatihan.lama_pelatihan,simpeg_data_pelatihan.catatan 
            FROM simpeg_data_pelatihan INNER JOIN simpeg_data_pegawai ON simpeg_data_pelatihan.id_pegawai = simpeg_data_pegawai.id_pegawai 
            INNER JOIN simpeg_master_lokasi_pelatihan ON simpeg_data_pelatihan.id_lokasi = simpeg_master_lokasi_pelatihan.id_lokasi INNER JOIN simpeg_master_pelatihan ON simpeg_data_pelatihan.id_pelatihan = simpeg_master_pelatihan.id_pelatihan 
            ORDER BY simpeg_data_pelatihan.tanggal DESC");
        return $getdata->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_data_pelatihan', $q);
	$this->db->or_like('id_pegawai', $q);
	$this->db->or_like('id_pelatihan', $q);
	$this->db->or_like('id_lokasi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('penyelenggara', $q);
	$this->db->or_like('lama_pelatihan', $q);
	$this->db->or_like('catatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_data_pelatihan', $q);
	$this->db->or_like('id_pegawai', $q);
	$this->db->or_like('id_pelatihan', $q);
	$this->db->or_like('id_lokasi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('penyelenggara', $q);
	$this->db->or_like('lama_pelatihan', $q);
	$this->db->or_like('catatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pelatihan_model.php */
/* Location: ./application/models/Pelatihan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-08 06:29:55 */
/* http://harviacode.com */