<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sip_master_sifat extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Model_master_sifat');
        chek_session();
        cek_menu();
    }

    public function index() {
        $sip_master_sifat = $this->Model_master_sifat->get_all();

        $data = array(
            'sip_master_sifat_data' => $sip_master_sifat
        );

        $this->template->display('sip_master_sifat_list', $data);
    }

    public function read($id) {
        $row = $this->Model_master_sifat->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'kode_sifat' => $row->kode_sifat,
                'sifat_surat' => $row->sifat_surat,
            );
            $this->template->display('sip_master_sifat_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sip_master_sifat'));
        }
    }

    public function create() {
        $data = array(
            'button' => 'Create',
            'action' => site_url('sip_master_sifat/create_action'),
            'id' => set_value('id'),
            'kode_sifat' => set_value('kode_sifat'),
            'sifat_surat' => set_value('sifat_surat'),
        );
        $this->template->display('sip_master_sifat_form', $data);
    }

    public function create_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'kode_sifat' => $this->input->post('kode_sifat', TRUE),
                'sifat_surat' => $this->input->post('sifat_surat', TRUE),
            );

            $this->Model_master_sifat->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('sip_master_sifat'));
        }
    }

    public function update($id) {
        $row = $this->Model_master_sifat->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('sip_master_sifat/update_action'),
                'id' => set_value('id', $row->id),
                'kode_sifat' => set_value('kode_sifat', $row->kode_sifat),
                'sifat_surat' => set_value('sifat_surat', $row->sifat_surat),
            );
            $this->template->display('sip_master_sifat_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sip_master_sifat'));
        }
    }

    public function update_action() {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'kode_sifat' => $this->input->post('kode_sifat', TRUE),
                'sifat_surat' => $this->input->post('sifat_surat', TRUE),
            );

            $this->Model_master_sifat->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('sip_master_sifat'));
        }
    }

    public function delete($id) {
        $row = $this->Model_master_sifat->get_by_id($id);

        if ($row) {
            $this->Model_master_sifat->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('sip_master_sifat'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sip_master_sifat'));
        }
    }

    public function _rules() {
        $this->form_validation->set_rules('kode_sifat', 'kode sifat', 'trim|required');
        $this->form_validation->set_rules('sifat_surat', 'sifat surat', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Sip_master_sifat.php */
/* Location: ./application/controllers/Sip_master_sifat.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-29 09:04:52 */
/* http://harviacode.com */